# Generated by Django 2.0.2 on 2018-02-22 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20180222_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='golangtutorial',
            name='go_solution_body',
            field=models.TextField(default='add something'),
        ),
        migrations.AddField(
            model_name='golangtutorial',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='golangtutorial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='golangtutorial',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecteularsolution',
            name='pe_solution_body',
            field=models.TextField(default='add some'),
        ),
        migrations.AddField(
            model_name='projecteularsolution',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projecteularsolution',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='projecteularsolution',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='py_solution_body',
            field=models.TextField(default='add something'),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
