# Generated by Django 2.0.2 on 2018-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20180222_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='golangtutorial',
            name='tuts_tag',
            field=models.CharField(default='Golang', max_length=250),
        ),
        migrations.AddField(
            model_name='projecteularsolution',
            name='tuts_tag',
            field=models.CharField(default='ProjectEular', max_length=250),
        ),
        migrations.AddField(
            model_name='pythontutorial',
            name='tuts_tag',
            field=models.CharField(default='Python', max_length=250),
        ),
    ]
