# Generated by Django 2.0.2 on 2018-02-09 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180209_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='code_tags',
            new_name='post_tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 22, 49, 592975, tzinfo=utc)),
        ),
    ]
