# Generated by Django 2.0.2 on 2018-02-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180210_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='null.png', upload_to='post'),
        ),
    ]
